# Generated by Django 6.1.1 on 2026-10-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bike_servise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=20)),
                ('service_date', models.IntegerField()),
                ('problem', models.CharField()),
                ('bike_no', models.CharField()),
                ('phon_no', models.IntegerField()),
                ('manufacturing_year', models.IntegerField()),
            ],
        ),
    ]
